{{config(materialized='table')}}
with tb1 as (
SELECT
C_CUSTKEY AS CUSTKEY,
C_NAME	AS NAME,
C_ADDRESS AS ADDRESS,
C_NATIONKEY	AS NATIONKEY,
C_PHONE	AS PHONE,
C_ACCTBAL AS ACCTBAL  ,
C_MKTSEGMENT AS MKTSEGMENT	,
C_COMMENT AS COMMENT
FROM {{source("Snowflake_Date",'RAW_CUSTOMER_NATION')}})
select * from tb1




